package com.skxd.vo;

import java.util.Date;

/**
 * Created by shang-pc on 2015/12/3.
 */
public class SkxdAnswerVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer.id
     *
     * @mbggenerated Wed Dec 02 22:18:46 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer.title
     *
     * @mbggenerated Wed Dec 02 22:18:46 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer.leader_id
     *
     * @mbggenerated Wed Dec 02 22:18:46 CST 2015
     */
    private String leaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer.project_id
     *
     * @mbggenerated Wed Dec 02 22:18:46 CST 2015
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer.device_id
     *
     * @mbggenerated Wed Dec 02 22:18:46 CST 2015
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer.user_id
     *
     * @mbggenerated Wed Dec 02 22:18:46 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer.status
     *
     * @mbggenerated Wed Dec 02 22:18:46 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer.created_date
     *
     * @mbggenerated Wed Dec 02 22:18:46 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer.updated_date
     *
     * @mbggenerated Wed Dec 02 22:18:46 CST 2015
     */
    private Date updatedDate;

    private String leaderName;


    private String userName; //工程师姓名
    private  String customName; //客户（用户）名称
    private  String deviceType; //仪器型号
    private String projectName; //工单名称


    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getCustomName() {
        return customName;
    }

    public void setCustomName(String customName) {
        this.customName = customName;
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getLeaderName() {
        return leaderName;
    }

    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLeaderId() {
        return leaderId;
    }

    public void setLeaderId(String leaderId) {
        this.leaderId = leaderId;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}
