package com.skxd.dao;

import com.skxd.model.SkxdTemplateProject;
import com.skxd.model.SkxdTemplateProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdTemplateProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int countByExample(SkxdTemplateProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int deleteByExample(SkxdTemplateProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int insert(SkxdTemplateProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int insertSelective(SkxdTemplateProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    List<SkxdTemplateProject> selectByExample(SkxdTemplateProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    SkxdTemplateProject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdTemplateProject record, @Param("example") SkxdTemplateProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExample(@Param("record") SkxdTemplateProject record, @Param("example") SkxdTemplateProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdTemplateProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKey(SkxdTemplateProject record);
}