package com.skxd.dao;

import com.skxd.model.SkxdFormTemplate;
import com.skxd.model.SkxdFormTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdFormTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int countByExample(SkxdFormTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int deleteByExample(SkxdFormTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int insert(SkxdFormTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int insertSelective(SkxdFormTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    List<SkxdFormTemplate> selectByExampleWithBLOBs(SkxdFormTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    List<SkxdFormTemplate> selectByExample(SkxdFormTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    SkxdFormTemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdFormTemplate record, @Param("example") SkxdFormTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") SkxdFormTemplate record, @Param("example") SkxdFormTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExample(@Param("record") SkxdFormTemplate record, @Param("example") SkxdFormTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdFormTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(SkxdFormTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKey(SkxdFormTemplate record);
}