package com.skxd.dao;

import com.skxd.model.SkxdAdminRole;
import com.skxd.model.SkxdAdminRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdAdminRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int countByExample(SkxdAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int deleteByExample(SkxdAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int insert(SkxdAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int insertSelective(SkxdAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    List<SkxdAdminRole> selectByExample(SkxdAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    SkxdAdminRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdAdminRole record, @Param("example") SkxdAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByExample(@Param("record") SkxdAdminRole record, @Param("example") SkxdAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByPrimaryKey(SkxdAdminRole record);
}