package com.skxd.dao;

import com.skxd.model.SkxdRole;
import com.skxd.model.SkxdRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int countByExample(SkxdRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int deleteByExample(SkxdRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int insert(SkxdRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int insertSelective(SkxdRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    List<SkxdRole> selectByExample(SkxdRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    SkxdRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdRole record, @Param("example") SkxdRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExample(@Param("record") SkxdRole record, @Param("example") SkxdRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKey(SkxdRole record);
}