package com.skxd.dao;

import com.skxd.model.SkxdAdminDictionary;
import com.skxd.model.SkxdAdminDictionaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdAdminDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int countByExample(SkxdAdminDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int deleteByExample(SkxdAdminDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int insert(SkxdAdminDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int insertSelective(SkxdAdminDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    List<SkxdAdminDictionary> selectByExample(SkxdAdminDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    SkxdAdminDictionary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") SkxdAdminDictionary record, @Param("example") SkxdAdminDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int updateByExample(@Param("record") SkxdAdminDictionary record, @Param("example") SkxdAdminDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int updateByPrimaryKeySelective(SkxdAdminDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int updateByPrimaryKey(SkxdAdminDictionary record);
}