package com.skxd.dao;

import com.skxd.model.SkxdUserPower;
import com.skxd.model.SkxdUserPowerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdUserPowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    int countByExample(SkxdUserPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    int deleteByExample(SkxdUserPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    int insert(SkxdUserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    int insertSelective(SkxdUserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    List<SkxdUserPower> selectByExample(SkxdUserPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    SkxdUserPower selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") SkxdUserPower record, @Param("example") SkxdUserPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    int updateByExample(@Param("record") SkxdUserPower record, @Param("example") SkxdUserPowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    int updateByPrimaryKeySelective(SkxdUserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    int updateByPrimaryKey(SkxdUserPower record);
}