package com.skxd.dao;

import com.skxd.model.SkxdAdminDictionaryValue;
import com.skxd.model.SkxdAdminDictionaryValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdAdminDictionaryValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int countByExample(SkxdAdminDictionaryValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int deleteByExample(SkxdAdminDictionaryValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int insert(SkxdAdminDictionaryValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int insertSelective(SkxdAdminDictionaryValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    List<SkxdAdminDictionaryValue> selectByExample(SkxdAdminDictionaryValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    SkxdAdminDictionaryValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") SkxdAdminDictionaryValue record, @Param("example") SkxdAdminDictionaryValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int updateByExample(@Param("record") SkxdAdminDictionaryValue record, @Param("example") SkxdAdminDictionaryValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int updateByPrimaryKeySelective(SkxdAdminDictionaryValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    int updateByPrimaryKey(SkxdAdminDictionaryValue record);
}