package com.skxd.dao;

import com.skxd.model.SkxdTemplateStep;
import com.skxd.model.SkxdTemplateStepExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdTemplateStepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    int countByExample(SkxdTemplateStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    int deleteByExample(SkxdTemplateStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    int insert(SkxdTemplateStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    int insertSelective(SkxdTemplateStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    List<SkxdTemplateStep> selectByExample(SkxdTemplateStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    SkxdTemplateStep selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdTemplateStep record, @Param("example") SkxdTemplateStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    int updateByExample(@Param("record") SkxdTemplateStep record, @Param("example") SkxdTemplateStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdTemplateStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    int updateByPrimaryKey(SkxdTemplateStep record);
}