package com.skxd.dao;

import com.skxd.model.SkxdAdminUser;
import com.skxd.model.SkxdAdminUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdAdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int countByExample(SkxdAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int deleteByExample(SkxdAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int insert(SkxdAdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int insertSelective(SkxdAdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    List<SkxdAdminUser> selectByExample(SkxdAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    SkxdAdminUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdAdminUser record, @Param("example") SkxdAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByExample(@Param("record") SkxdAdminUser record, @Param("example") SkxdAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdAdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByPrimaryKey(SkxdAdminUser record);
}