package com.skxd.dao;

import com.skxd.model.SkxdArea;
import com.skxd.model.SkxdAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int countByExample(SkxdAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int deleteByExample(SkxdAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int insert(SkxdArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int insertSelective(SkxdArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    List<SkxdArea> selectByExample(SkxdAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    SkxdArea selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdArea record, @Param("example") SkxdAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByExample(@Param("record") SkxdArea record, @Param("example") SkxdAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByPrimaryKey(SkxdArea record);
}