package com.skxd.dao;

import com.skxd.model.SkxdTemplateInputType;
import com.skxd.model.SkxdTemplateInputTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdTemplateInputTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int countByExample(SkxdTemplateInputTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int deleteByExample(SkxdTemplateInputTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int insert(SkxdTemplateInputType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int insertSelective(SkxdTemplateInputType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    List<SkxdTemplateInputType> selectByExample(SkxdTemplateInputTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    SkxdTemplateInputType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdTemplateInputType record, @Param("example") SkxdTemplateInputTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExample(@Param("record") SkxdTemplateInputType record, @Param("example") SkxdTemplateInputTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdTemplateInputType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKey(SkxdTemplateInputType record);
}