package com.skxd.dao;

import com.skxd.model.SkxdDepartment;
import com.skxd.model.SkxdDepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int countByExample(SkxdDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int deleteByExample(SkxdDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int insert(SkxdDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int insertSelective(SkxdDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    List<SkxdDepartment> selectByExample(SkxdDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    SkxdDepartment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdDepartment record, @Param("example") SkxdDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByExample(@Param("record") SkxdDepartment record, @Param("example") SkxdDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    int updateByPrimaryKey(SkxdDepartment record);
}