package com.skxd.dao;

import com.skxd.model.SkxdAdminUserRole;
import com.skxd.model.SkxdAdminUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdAdminUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    int countByExample(SkxdAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    int deleteByExample(SkxdAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    int insert(SkxdAdminUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    int insertSelective(SkxdAdminUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    List<SkxdAdminUserRole> selectByExample(SkxdAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    SkxdAdminUserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdAdminUserRole record, @Param("example") SkxdAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    int updateByExample(@Param("record") SkxdAdminUserRole record, @Param("example") SkxdAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdAdminUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    int updateByPrimaryKey(SkxdAdminUserRole record);
}