package com.skxd.dao;

import com.skxd.model.SkxdAdminRoleModule;
import com.skxd.model.SkxdAdminRoleModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdAdminRoleModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int countByExample(SkxdAdminRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int deleteByExample(SkxdAdminRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int insert(SkxdAdminRoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int insertSelective(SkxdAdminRoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    List<SkxdAdminRoleModule> selectByExample(SkxdAdminRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    SkxdAdminRoleModule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdAdminRoleModule record, @Param("example") SkxdAdminRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByExample(@Param("record") SkxdAdminRoleModule record, @Param("example") SkxdAdminRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdAdminRoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByPrimaryKey(SkxdAdminRoleModule record);
}