package com.skxd.dao;

import com.skxd.model.SkxdAnswerValue;
import com.skxd.model.SkxdAnswerValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkxdAnswerValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int countByExample(SkxdAnswerValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int deleteByExample(SkxdAnswerValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int insert(SkxdAnswerValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int insertSelective(SkxdAnswerValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    List<SkxdAnswerValue> selectByExample(SkxdAnswerValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    SkxdAnswerValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") SkxdAnswerValue record, @Param("example") SkxdAnswerValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByExample(@Param("record") SkxdAnswerValue record, @Param("example") SkxdAnswerValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByPrimaryKeySelective(SkxdAnswerValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    int updateByPrimaryKey(SkxdAnswerValue record);
}