package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdTemplateProject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_project.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_project.name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_project.remark
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_project.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_project.updated_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_project.created_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_project.updated_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String updatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_template_project
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_project.id
     *
     * @return the value of skxd_template_project.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_project.id
     *
     * @param id the value for skxd_template_project.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_project.name
     *
     * @return the value of skxd_template_project.name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_project.name
     *
     * @param name the value for skxd_template_project.name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_project.remark
     *
     * @return the value of skxd_template_project.remark
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_project.remark
     *
     * @param remark the value for skxd_template_project.remark
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_project.created_date
     *
     * @return the value of skxd_template_project.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_project.created_date
     *
     * @param createdDate the value for skxd_template_project.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_project.updated_date
     *
     * @return the value of skxd_template_project.updated_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_project.updated_date
     *
     * @param updatedDate the value for skxd_template_project.updated_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_project.created_user
     *
     * @return the value of skxd_template_project.created_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_project.created_user
     *
     * @param createdUser the value for skxd_template_project.created_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_project.updated_user
     *
     * @return the value of skxd_template_project.updated_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_project.updated_user
     *
     * @param updatedUser the value for skxd_template_project.updated_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }
}