package com.skxd.model;

import java.io.Serializable;

public class SkxdTemplateInputType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_input_type.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_input_type.input_type_name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String inputTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_input_type.type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_template_input_type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_input_type.id
     *
     * @return the value of skxd_template_input_type.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_input_type.id
     *
     * @param id the value for skxd_template_input_type.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_input_type.input_type_name
     *
     * @return the value of skxd_template_input_type.input_type_name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getInputTypeName() {
        return inputTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_input_type.input_type_name
     *
     * @param inputTypeName the value for skxd_template_input_type.input_type_name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setInputTypeName(String inputTypeName) {
        this.inputTypeName = inputTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_input_type.type
     *
     * @return the value of skxd_template_input_type.type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_input_type.type
     *
     * @param type the value for skxd_template_input_type.type
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }
}