package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdUserPower implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.user_id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.province_no
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private String provinceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.province_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private String provinceNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.city_no
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private String cityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.city_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private String cityNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.custom_id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private String customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.custom_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private String customNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.device_id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.device_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private String deviceNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.created_time
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_power.updated_time
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_user_power
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.id
     *
     * @return the value of skxd_user_power.id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.id
     *
     * @param id the value for skxd_user_power.id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.user_id
     *
     * @return the value of skxd_user_power.user_id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.user_id
     *
     * @param userId the value for skxd_user_power.user_id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.province_no
     *
     * @return the value of skxd_user_power.province_no
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public String getProvinceNo() {
        return provinceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.province_no
     *
     * @param provinceNo the value for skxd_user_power.province_no
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setProvinceNo(String provinceNo) {
        this.provinceNo = provinceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.province_names
     *
     * @return the value of skxd_user_power.province_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public String getProvinceNames() {
        return provinceNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.province_names
     *
     * @param provinceNames the value for skxd_user_power.province_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setProvinceNames(String provinceNames) {
        this.provinceNames = provinceNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.city_no
     *
     * @return the value of skxd_user_power.city_no
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public String getCityNo() {
        return cityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.city_no
     *
     * @param cityNo the value for skxd_user_power.city_no
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setCityNo(String cityNo) {
        this.cityNo = cityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.city_names
     *
     * @return the value of skxd_user_power.city_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public String getCityNames() {
        return cityNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.city_names
     *
     * @param cityNames the value for skxd_user_power.city_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setCityNames(String cityNames) {
        this.cityNames = cityNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.custom_id
     *
     * @return the value of skxd_user_power.custom_id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public String getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.custom_id
     *
     * @param customId the value for skxd_user_power.custom_id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setCustomId(String customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.custom_names
     *
     * @return the value of skxd_user_power.custom_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public String getCustomNames() {
        return customNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.custom_names
     *
     * @param customNames the value for skxd_user_power.custom_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setCustomNames(String customNames) {
        this.customNames = customNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.device_id
     *
     * @return the value of skxd_user_power.device_id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.device_id
     *
     * @param deviceId the value for skxd_user_power.device_id
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.device_names
     *
     * @return the value of skxd_user_power.device_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public String getDeviceNames() {
        return deviceNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.device_names
     *
     * @param deviceNames the value for skxd_user_power.device_names
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setDeviceNames(String deviceNames) {
        this.deviceNames = deviceNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.created_time
     *
     * @return the value of skxd_user_power.created_time
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.created_time
     *
     * @param createdTime the value for skxd_user_power.created_time
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_power.updated_time
     *
     * @return the value of skxd_user_power.updated_time
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_power.updated_time
     *
     * @param updatedTime the value for skxd_user_power.updated_time
     *
     * @mbggenerated Mon May 16 22:35:17 CST 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}