package com.skxd.model;

import java.io.Serializable;

public class SkxdArea implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_area.id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_area.name
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_area.area_no
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String areaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_area.parent
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_area.is_activated
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private Integer isActivated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_area.level
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_area
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_area.id
     *
     * @return the value of skxd_area.id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_area.id
     *
     * @param id the value for skxd_area.id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_area.name
     *
     * @return the value of skxd_area.name
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_area.name
     *
     * @param name the value for skxd_area.name
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_area.area_no
     *
     * @return the value of skxd_area.area_no
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getAreaNo() {
        return areaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_area.area_no
     *
     * @param areaNo the value for skxd_area.area_no
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setAreaNo(String areaNo) {
        this.areaNo = areaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_area.parent
     *
     * @return the value of skxd_area.parent
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_area.parent
     *
     * @param parent the value for skxd_area.parent
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setParent(String parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_area.is_activated
     *
     * @return the value of skxd_area.is_activated
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public Integer getIsActivated() {
        return isActivated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_area.is_activated
     *
     * @param isActivated the value for skxd_area.is_activated
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setIsActivated(Integer isActivated) {
        this.isActivated = isActivated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_area.level
     *
     * @return the value of skxd_area.level
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_area.level
     *
     * @param level the value for skxd_area.level
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}