package com.skxd.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SkxdQuarterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public SkxdQuarterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCustomIdIsNull() {
            addCriterion("custom_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomIdIsNotNull() {
            addCriterion("custom_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomIdEqualTo(String value) {
            addCriterion("custom_id =", value, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdNotEqualTo(String value) {
            addCriterion("custom_id <>", value, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdGreaterThan(String value) {
            addCriterion("custom_id >", value, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdGreaterThanOrEqualTo(String value) {
            addCriterion("custom_id >=", value, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdLessThan(String value) {
            addCriterion("custom_id <", value, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdLessThanOrEqualTo(String value) {
            addCriterion("custom_id <=", value, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdLike(String value) {
            addCriterion("custom_id like", value, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdNotLike(String value) {
            addCriterion("custom_id not like", value, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdIn(List<String> values) {
            addCriterion("custom_id in", values, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdNotIn(List<String> values) {
            addCriterion("custom_id not in", values, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdBetween(String value1, String value2) {
            addCriterion("custom_id between", value1, value2, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomIdNotBetween(String value1, String value2) {
            addCriterion("custom_id not between", value1, value2, "customId");
            return (Criteria) this;
        }

        public Criteria andCustomNameIsNull() {
            addCriterion("custom_name is null");
            return (Criteria) this;
        }

        public Criteria andCustomNameIsNotNull() {
            addCriterion("custom_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustomNameEqualTo(String value) {
            addCriterion("custom_name =", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameNotEqualTo(String value) {
            addCriterion("custom_name <>", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameGreaterThan(String value) {
            addCriterion("custom_name >", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameGreaterThanOrEqualTo(String value) {
            addCriterion("custom_name >=", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameLessThan(String value) {
            addCriterion("custom_name <", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameLessThanOrEqualTo(String value) {
            addCriterion("custom_name <=", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameLike(String value) {
            addCriterion("custom_name like", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameNotLike(String value) {
            addCriterion("custom_name not like", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameIn(List<String> values) {
            addCriterion("custom_name in", values, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameNotIn(List<String> values) {
            addCriterion("custom_name not in", values, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameBetween(String value1, String value2) {
            addCriterion("custom_name between", value1, value2, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameNotBetween(String value1, String value2) {
            addCriterion("custom_name not between", value1, value2, "customName");
            return (Criteria) this;
        }

        public Criteria andStaticTypeIsNull() {
            addCriterion("static_type is null");
            return (Criteria) this;
        }

        public Criteria andStaticTypeIsNotNull() {
            addCriterion("static_type is not null");
            return (Criteria) this;
        }

        public Criteria andStaticTypeEqualTo(String value) {
            addCriterion("static_type =", value, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeNotEqualTo(String value) {
            addCriterion("static_type <>", value, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeGreaterThan(String value) {
            addCriterion("static_type >", value, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeGreaterThanOrEqualTo(String value) {
            addCriterion("static_type >=", value, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeLessThan(String value) {
            addCriterion("static_type <", value, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeLessThanOrEqualTo(String value) {
            addCriterion("static_type <=", value, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeLike(String value) {
            addCriterion("static_type like", value, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeNotLike(String value) {
            addCriterion("static_type not like", value, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeIn(List<String> values) {
            addCriterion("static_type in", values, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeNotIn(List<String> values) {
            addCriterion("static_type not in", values, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeBetween(String value1, String value2) {
            addCriterion("static_type between", value1, value2, "staticType");
            return (Criteria) this;
        }

        public Criteria andStaticTypeNotBetween(String value1, String value2) {
            addCriterion("static_type not between", value1, value2, "staticType");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andSpringIsNull() {
            addCriterion("spring is null");
            return (Criteria) this;
        }

        public Criteria andSpringIsNotNull() {
            addCriterion("spring is not null");
            return (Criteria) this;
        }

        public Criteria andSpringEqualTo(Double value) {
            addCriterion("spring =", value, "spring");
            return (Criteria) this;
        }

        public Criteria andSpringNotEqualTo(Double value) {
            addCriterion("spring <>", value, "spring");
            return (Criteria) this;
        }

        public Criteria andSpringGreaterThan(Double value) {
            addCriterion("spring >", value, "spring");
            return (Criteria) this;
        }

        public Criteria andSpringGreaterThanOrEqualTo(Double value) {
            addCriterion("spring >=", value, "spring");
            return (Criteria) this;
        }

        public Criteria andSpringLessThan(Double value) {
            addCriterion("spring <", value, "spring");
            return (Criteria) this;
        }

        public Criteria andSpringLessThanOrEqualTo(Double value) {
            addCriterion("spring <=", value, "spring");
            return (Criteria) this;
        }

        public Criteria andSpringIn(List<Double> values) {
            addCriterion("spring in", values, "spring");
            return (Criteria) this;
        }

        public Criteria andSpringNotIn(List<Double> values) {
            addCriterion("spring not in", values, "spring");
            return (Criteria) this;
        }

        public Criteria andSpringBetween(Double value1, Double value2) {
            addCriterion("spring between", value1, value2, "spring");
            return (Criteria) this;
        }

        public Criteria andSpringNotBetween(Double value1, Double value2) {
            addCriterion("spring not between", value1, value2, "spring");
            return (Criteria) this;
        }

        public Criteria andSummerIsNull() {
            addCriterion("summer is null");
            return (Criteria) this;
        }

        public Criteria andSummerIsNotNull() {
            addCriterion("summer is not null");
            return (Criteria) this;
        }

        public Criteria andSummerEqualTo(Double value) {
            addCriterion("summer =", value, "summer");
            return (Criteria) this;
        }

        public Criteria andSummerNotEqualTo(Double value) {
            addCriterion("summer <>", value, "summer");
            return (Criteria) this;
        }

        public Criteria andSummerGreaterThan(Double value) {
            addCriterion("summer >", value, "summer");
            return (Criteria) this;
        }

        public Criteria andSummerGreaterThanOrEqualTo(Double value) {
            addCriterion("summer >=", value, "summer");
            return (Criteria) this;
        }

        public Criteria andSummerLessThan(Double value) {
            addCriterion("summer <", value, "summer");
            return (Criteria) this;
        }

        public Criteria andSummerLessThanOrEqualTo(Double value) {
            addCriterion("summer <=", value, "summer");
            return (Criteria) this;
        }

        public Criteria andSummerIn(List<Double> values) {
            addCriterion("summer in", values, "summer");
            return (Criteria) this;
        }

        public Criteria andSummerNotIn(List<Double> values) {
            addCriterion("summer not in", values, "summer");
            return (Criteria) this;
        }

        public Criteria andSummerBetween(Double value1, Double value2) {
            addCriterion("summer between", value1, value2, "summer");
            return (Criteria) this;
        }

        public Criteria andSummerNotBetween(Double value1, Double value2) {
            addCriterion("summer not between", value1, value2, "summer");
            return (Criteria) this;
        }

        public Criteria andAutumnIsNull() {
            addCriterion("autumn is null");
            return (Criteria) this;
        }

        public Criteria andAutumnIsNotNull() {
            addCriterion("autumn is not null");
            return (Criteria) this;
        }

        public Criteria andAutumnEqualTo(Double value) {
            addCriterion("autumn =", value, "autumn");
            return (Criteria) this;
        }

        public Criteria andAutumnNotEqualTo(Double value) {
            addCriterion("autumn <>", value, "autumn");
            return (Criteria) this;
        }

        public Criteria andAutumnGreaterThan(Double value) {
            addCriterion("autumn >", value, "autumn");
            return (Criteria) this;
        }

        public Criteria andAutumnGreaterThanOrEqualTo(Double value) {
            addCriterion("autumn >=", value, "autumn");
            return (Criteria) this;
        }

        public Criteria andAutumnLessThan(Double value) {
            addCriterion("autumn <", value, "autumn");
            return (Criteria) this;
        }

        public Criteria andAutumnLessThanOrEqualTo(Double value) {
            addCriterion("autumn <=", value, "autumn");
            return (Criteria) this;
        }

        public Criteria andAutumnIn(List<Double> values) {
            addCriterion("autumn in", values, "autumn");
            return (Criteria) this;
        }

        public Criteria andAutumnNotIn(List<Double> values) {
            addCriterion("autumn not in", values, "autumn");
            return (Criteria) this;
        }

        public Criteria andAutumnBetween(Double value1, Double value2) {
            addCriterion("autumn between", value1, value2, "autumn");
            return (Criteria) this;
        }

        public Criteria andAutumnNotBetween(Double value1, Double value2) {
            addCriterion("autumn not between", value1, value2, "autumn");
            return (Criteria) this;
        }

        public Criteria andWinterIsNull() {
            addCriterion("winter is null");
            return (Criteria) this;
        }

        public Criteria andWinterIsNotNull() {
            addCriterion("winter is not null");
            return (Criteria) this;
        }

        public Criteria andWinterEqualTo(Double value) {
            addCriterion("winter =", value, "winter");
            return (Criteria) this;
        }

        public Criteria andWinterNotEqualTo(Double value) {
            addCriterion("winter <>", value, "winter");
            return (Criteria) this;
        }

        public Criteria andWinterGreaterThan(Double value) {
            addCriterion("winter >", value, "winter");
            return (Criteria) this;
        }

        public Criteria andWinterGreaterThanOrEqualTo(Double value) {
            addCriterion("winter >=", value, "winter");
            return (Criteria) this;
        }

        public Criteria andWinterLessThan(Double value) {
            addCriterion("winter <", value, "winter");
            return (Criteria) this;
        }

        public Criteria andWinterLessThanOrEqualTo(Double value) {
            addCriterion("winter <=", value, "winter");
            return (Criteria) this;
        }

        public Criteria andWinterIn(List<Double> values) {
            addCriterion("winter in", values, "winter");
            return (Criteria) this;
        }

        public Criteria andWinterNotIn(List<Double> values) {
            addCriterion("winter not in", values, "winter");
            return (Criteria) this;
        }

        public Criteria andWinterBetween(Double value1, Double value2) {
            addCriterion("winter between", value1, value2, "winter");
            return (Criteria) this;
        }

        public Criteria andWinterNotBetween(Double value1, Double value2) {
            addCriterion("winter not between", value1, value2, "winter");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skxd_quarter
     *
     * @mbggenerated do_not_delete_during_merge Sat Jul 02 19:49:52 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}