package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdMessage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_message.id
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_message.title
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_message.content
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_message.recipient
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private String recipient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_message.sender_id
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private String senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_message.created_user_id
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private String createdUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_message.sender_name
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private String senderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_message.created_date
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_message.message_type
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private String messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_message.updated_date
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_message
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_message.id
     *
     * @return the value of skxd_message.id
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_message.id
     *
     * @param id the value for skxd_message.id
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_message.title
     *
     * @return the value of skxd_message.title
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_message.title
     *
     * @param title the value for skxd_message.title
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_message.content
     *
     * @return the value of skxd_message.content
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_message.content
     *
     * @param content the value for skxd_message.content
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_message.recipient
     *
     * @return the value of skxd_message.recipient
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public String getRecipient() {
        return recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_message.recipient
     *
     * @param recipient the value for skxd_message.recipient
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public void setRecipient(String recipient) {
        this.recipient = recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_message.sender_id
     *
     * @return the value of skxd_message.sender_id
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_message.sender_id
     *
     * @param senderId the value for skxd_message.sender_id
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_message.created_user_id
     *
     * @return the value of skxd_message.created_user_id
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_message.created_user_id
     *
     * @param createdUserId the value for skxd_message.created_user_id
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_message.sender_name
     *
     * @return the value of skxd_message.sender_name
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_message.sender_name
     *
     * @param senderName the value for skxd_message.sender_name
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_message.created_date
     *
     * @return the value of skxd_message.created_date
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_message.created_date
     *
     * @param createdDate the value for skxd_message.created_date
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_message.message_type
     *
     * @return the value of skxd_message.message_type
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_message.message_type
     *
     * @param messageType the value for skxd_message.message_type
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_message.updated_date
     *
     * @return the value of skxd_message.updated_date
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_message.updated_date
     *
     * @param updatedDate the value for skxd_message.updated_date
     *
     * @mbggenerated Sun Nov 29 21:24:30 CST 2015
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}