package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdQuarter implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.id
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.custom_id
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private String customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.custom_name
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private String customName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.static_type
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private String staticType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.name
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.year
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.spring
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private Double spring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.summer
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private Double summer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.autumn
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private Double autumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.winter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private Double winter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_quarter.created_time
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_quarter
     *
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.id
     *
     * @return the value of skxd_quarter.id
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.id
     *
     * @param id the value for skxd_quarter.id
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.custom_id
     *
     * @return the value of skxd_quarter.custom_id
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public String getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.custom_id
     *
     * @param customId the value for skxd_quarter.custom_id
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setCustomId(String customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.custom_name
     *
     * @return the value of skxd_quarter.custom_name
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.custom_name
     *
     * @param customName the value for skxd_quarter.custom_name
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setCustomName(String customName) {
        this.customName = customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.static_type
     *
     * @return the value of skxd_quarter.static_type
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public String getStaticType() {
        return staticType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.static_type
     *
     * @param staticType the value for skxd_quarter.static_type
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setStaticType(String staticType) {
        this.staticType = staticType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.name
     *
     * @return the value of skxd_quarter.name
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.name
     *
     * @param name the value for skxd_quarter.name
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.year
     *
     * @return the value of skxd_quarter.year
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.year
     *
     * @param year the value for skxd_quarter.year
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.spring
     *
     * @return the value of skxd_quarter.spring
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public Double getSpring() {
        return spring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.spring
     *
     * @param spring the value for skxd_quarter.spring
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setSpring(Double spring) {
        this.spring = spring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.summer
     *
     * @return the value of skxd_quarter.summer
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public Double getSummer() {
        return summer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.summer
     *
     * @param summer the value for skxd_quarter.summer
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setSummer(Double summer) {
        this.summer = summer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.autumn
     *
     * @return the value of skxd_quarter.autumn
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public Double getAutumn() {
        return autumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.autumn
     *
     * @param autumn the value for skxd_quarter.autumn
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setAutumn(Double autumn) {
        this.autumn = autumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.winter
     *
     * @return the value of skxd_quarter.winter
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public Double getWinter() {
        return winter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.winter
     *
     * @param winter the value for skxd_quarter.winter
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setWinter(Double winter) {
        this.winter = winter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_quarter.created_time
     *
     * @return the value of skxd_quarter.created_time
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_quarter.created_time
     *
     * @param createdTime the value for skxd_quarter.created_time
     * @mbggenerated Sat Jul 02 19:49:52 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public SkxdQuarter(String name) {
        this.name = name;
        this.spring = 0.0;
        this.summer = 0.0;
        this.autumn = 0.0;
        this.winter = 0.0;
    }
    public SkxdQuarter() {

    }
}