package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdAdminUserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_user_role.id
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_user_role.user_id
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_user_role.role_id
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_user_role.created_user
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_user_role.created_date
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_user_role.updated_user
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    private String updatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_user_role.updated_date
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_admin_user_role
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_user_role.id
     *
     * @return the value of skxd_admin_user_role.id
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_user_role.id
     *
     * @param id the value for skxd_admin_user_role.id
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_user_role.user_id
     *
     * @return the value of skxd_admin_user_role.user_id
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_user_role.user_id
     *
     * @param userId the value for skxd_admin_user_role.user_id
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_user_role.role_id
     *
     * @return the value of skxd_admin_user_role.role_id
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_user_role.role_id
     *
     * @param roleId the value for skxd_admin_user_role.role_id
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_user_role.created_user
     *
     * @return the value of skxd_admin_user_role.created_user
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_user_role.created_user
     *
     * @param createdUser the value for skxd_admin_user_role.created_user
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_user_role.created_date
     *
     * @return the value of skxd_admin_user_role.created_date
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_user_role.created_date
     *
     * @param createdDate the value for skxd_admin_user_role.created_date
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_user_role.updated_user
     *
     * @return the value of skxd_admin_user_role.updated_user
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_user_role.updated_user
     *
     * @param updatedUser the value for skxd_admin_user_role.updated_user
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_user_role.updated_date
     *
     * @return the value of skxd_admin_user_role.updated_date
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_user_role.updated_date
     *
     * @param updatedDate the value for skxd_admin_user_role.updated_date
     *
     * @mbggenerated Sat Nov 28 12:02:36 CST 2015
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}