package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdTemplateStep implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_step.id
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_step.step_name
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private String stepName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_step.project_id
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_step.sort
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_step.next
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private String next;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_step.pre
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private String pre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_step.created_user
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_step.updated_user
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private String updatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_step.created_date
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_template_step.updated_date
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_template_step
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_step.id
     *
     * @return the value of skxd_template_step.id
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_step.id
     *
     * @param id the value for skxd_template_step.id
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_step.step_name
     *
     * @return the value of skxd_template_step.step_name
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public String getStepName() {
        return stepName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_step.step_name
     *
     * @param stepName the value for skxd_template_step.step_name
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public void setStepName(String stepName) {
        this.stepName = stepName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_step.project_id
     *
     * @return the value of skxd_template_step.project_id
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_step.project_id
     *
     * @param projectId the value for skxd_template_step.project_id
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_step.sort
     *
     * @return the value of skxd_template_step.sort
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_step.sort
     *
     * @param sort the value for skxd_template_step.sort
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_step.next
     *
     * @return the value of skxd_template_step.next
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public String getNext() {
        return next;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_step.next
     *
     * @param next the value for skxd_template_step.next
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public void setNext(String next) {
        this.next = next;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_step.pre
     *
     * @return the value of skxd_template_step.pre
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public String getPre() {
        return pre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_step.pre
     *
     * @param pre the value for skxd_template_step.pre
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public void setPre(String pre) {
        this.pre = pre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_step.created_user
     *
     * @return the value of skxd_template_step.created_user
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_step.created_user
     *
     * @param createdUser the value for skxd_template_step.created_user
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_step.updated_user
     *
     * @return the value of skxd_template_step.updated_user
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_step.updated_user
     *
     * @param updatedUser the value for skxd_template_step.updated_user
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_step.created_date
     *
     * @return the value of skxd_template_step.created_date
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_step.created_date
     *
     * @param createdDate the value for skxd_template_step.created_date
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_template_step.updated_date
     *
     * @return the value of skxd_template_step.updated_date
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_template_step.updated_date
     *
     * @param updatedDate the value for skxd_template_step.updated_date
     *
     * @mbggenerated Fri Nov 27 13:29:44 CST 2015
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}