package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdAdminDictionaryValue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_dictionary_value.id
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_dictionary_value.name
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_dictionary_value.d_id
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    private String dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_dictionary_value.created_time
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_dictionary_value.updated_time
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_admin_dictionary_value
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_dictionary_value.id
     *
     * @return the value of skxd_admin_dictionary_value.id
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_dictionary_value.id
     *
     * @param id the value for skxd_admin_dictionary_value.id
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_dictionary_value.name
     *
     * @return the value of skxd_admin_dictionary_value.name
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_dictionary_value.name
     *
     * @param name the value for skxd_admin_dictionary_value.name
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_dictionary_value.d_id
     *
     * @return the value of skxd_admin_dictionary_value.d_id
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    public String getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_dictionary_value.d_id
     *
     * @param dId the value for skxd_admin_dictionary_value.d_id
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    public void setdId(String dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_dictionary_value.created_time
     *
     * @return the value of skxd_admin_dictionary_value.created_time
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_dictionary_value.created_time
     *
     * @param createdTime the value for skxd_admin_dictionary_value.created_time
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_dictionary_value.updated_time
     *
     * @return the value of skxd_admin_dictionary_value.updated_time
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_dictionary_value.updated_time
     *
     * @param updatedTime the value for skxd_admin_dictionary_value.updated_time
     *
     * @mbggenerated Sun May 22 18:51:58 CST 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}