package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdUserPosition implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_position.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_position.user_id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_position.longitude
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_position.latitude
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_user_position.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_user_position
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_position.id
     *
     * @return the value of skxd_user_position.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_position.id
     *
     * @param id the value for skxd_user_position.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_position.user_id
     *
     * @return the value of skxd_user_position.user_id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_position.user_id
     *
     * @param userId the value for skxd_user_position.user_id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_position.longitude
     *
     * @return the value of skxd_user_position.longitude
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_position.longitude
     *
     * @param longitude the value for skxd_user_position.longitude
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_position.latitude
     *
     * @return the value of skxd_user_position.latitude
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_position.latitude
     *
     * @param latitude the value for skxd_user_position.latitude
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_user_position.created_date
     *
     * @return the value of skxd_user_position.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_user_position.created_date
     *
     * @param createdDate the value for skxd_user_position.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}