package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdDepartment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_department.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_department.department_name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_department.created_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_department.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_department.updated_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String updatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_department.updated_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_department
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_department.id
     *
     * @return the value of skxd_department.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_department.id
     *
     * @param id the value for skxd_department.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_department.department_name
     *
     * @return the value of skxd_department.department_name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_department.department_name
     *
     * @param departmentName the value for skxd_department.department_name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_department.created_user
     *
     * @return the value of skxd_department.created_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_department.created_user
     *
     * @param createdUser the value for skxd_department.created_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_department.created_date
     *
     * @return the value of skxd_department.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_department.created_date
     *
     * @param createdDate the value for skxd_department.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_department.updated_user
     *
     * @return the value of skxd_department.updated_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_department.updated_user
     *
     * @param updatedUser the value for skxd_department.updated_user
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_department.updated_date
     *
     * @return the value of skxd_department.updated_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_department.updated_date
     *
     * @param updatedDate the value for skxd_department.updated_date
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}