package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdTask implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_task.id
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_task.task_title
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    private String taskTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_task.task_content
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    private String taskContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_task.created_date
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_task.created_user
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_task.updated_date
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_task.updated_user
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    private String updatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_task.created_user_name
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    private String createdUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_task
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_task.id
     *
     * @return the value of skxd_task.id
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_task.id
     *
     * @param id the value for skxd_task.id
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_task.task_title
     *
     * @return the value of skxd_task.task_title
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public String getTaskTitle() {
        return taskTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_task.task_title
     *
     * @param taskTitle the value for skxd_task.task_title
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public void setTaskTitle(String taskTitle) {
        this.taskTitle = taskTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_task.task_content
     *
     * @return the value of skxd_task.task_content
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public String getTaskContent() {
        return taskContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_task.task_content
     *
     * @param taskContent the value for skxd_task.task_content
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public void setTaskContent(String taskContent) {
        this.taskContent = taskContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_task.created_date
     *
     * @return the value of skxd_task.created_date
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_task.created_date
     *
     * @param createdDate the value for skxd_task.created_date
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_task.created_user
     *
     * @return the value of skxd_task.created_user
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_task.created_user
     *
     * @param createdUser the value for skxd_task.created_user
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_task.updated_date
     *
     * @return the value of skxd_task.updated_date
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_task.updated_date
     *
     * @param updatedDate the value for skxd_task.updated_date
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_task.updated_user
     *
     * @return the value of skxd_task.updated_user
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_task.updated_user
     *
     * @param updatedUser the value for skxd_task.updated_user
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_task.created_user_name
     *
     * @return the value of skxd_task.created_user_name
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public String getCreatedUserName() {
        return createdUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_task.created_user_name
     *
     * @param createdUserName the value for skxd_task.created_user_name
     *
     * @mbggenerated Sun Nov 29 18:27:24 CST 2015
     */
    public void setCreatedUserName(String createdUserName) {
        this.createdUserName = createdUserName;
    }
}