package com.skxd.model;

import java.io.Serializable;

public class SkxdRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_role.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_role.role_name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_role
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_role.id
     *
     * @return the value of skxd_role.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_role.id
     *
     * @param id the value for skxd_role.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_role.role_name
     *
     * @return the value of skxd_role.role_name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_role.role_name
     *
     * @param roleName the value for skxd_role.role_name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}