package com.skxd.model;

import java.io.Serializable;

public class SkxdFormTemplate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_form_template.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_form_template.name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_form_template.content
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_form_template
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_form_template.id
     *
     * @return the value of skxd_form_template.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_form_template.id
     *
     * @param id the value for skxd_form_template.id
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_form_template.name
     *
     * @return the value of skxd_form_template.name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_form_template.name
     *
     * @param name the value for skxd_form_template.name
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_form_template.content
     *
     * @return the value of skxd_form_template.content
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_form_template.content
     *
     * @param content the value for skxd_form_template.content
     *
     * @mbggenerated Sun Nov 29 11:26:05 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}