package com.skxd.model;

import java.io.Serializable;

public class SkxdAnswerValue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer_value.id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer_value.answer_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String answerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer_value.input_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String inputId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer_value.input_name
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String inputName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer_value.input_type
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String inputType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_answer_value.value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_answer_value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_answer_value.id
     *
     * @return the value of skxd_answer_value.id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_answer_value.id
     *
     * @param id the value for skxd_answer_value.id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_answer_value.answer_id
     *
     * @return the value of skxd_answer_value.answer_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_answer_value.answer_id
     *
     * @param answerId the value for skxd_answer_value.answer_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setAnswerId(String answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_answer_value.input_id
     *
     * @return the value of skxd_answer_value.input_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getInputId() {
        return inputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_answer_value.input_id
     *
     * @param inputId the value for skxd_answer_value.input_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setInputId(String inputId) {
        this.inputId = inputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_answer_value.input_name
     *
     * @return the value of skxd_answer_value.input_name
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getInputName() {
        return inputName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_answer_value.input_name
     *
     * @param inputName the value for skxd_answer_value.input_name
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setInputName(String inputName) {
        this.inputName = inputName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_answer_value.input_type
     *
     * @return the value of skxd_answer_value.input_type
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_answer_value.input_type
     *
     * @param inputType the value for skxd_answer_value.input_type
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setInputType(String inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_answer_value.value
     *
     * @return the value of skxd_answer_value.value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_answer_value.value
     *
     * @param value the value for skxd_answer_value.value
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setValue(String value) {
        this.value = value;
    }
}