package com.skxd.model;

import java.io.Serializable;
import java.util.Date;

public class SkxdAdminRoleModule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_role_module.id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_role_module.role_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_role_module.module_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_role_module.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_role_module.updated_date
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_role_module.created_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skxd_admin_role_module.updated_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private String updatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skxd_admin_role_module
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_role_module.id
     *
     * @return the value of skxd_admin_role_module.id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_role_module.id
     *
     * @param id the value for skxd_admin_role_module.id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_role_module.role_id
     *
     * @return the value of skxd_admin_role_module.role_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_role_module.role_id
     *
     * @param roleId the value for skxd_admin_role_module.role_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_role_module.module_id
     *
     * @return the value of skxd_admin_role_module.module_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_role_module.module_id
     *
     * @param moduleId the value for skxd_admin_role_module.module_id
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_role_module.created_date
     *
     * @return the value of skxd_admin_role_module.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_role_module.created_date
     *
     * @param createdDate the value for skxd_admin_role_module.created_date
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_role_module.updated_date
     *
     * @return the value of skxd_admin_role_module.updated_date
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_role_module.updated_date
     *
     * @param updatedDate the value for skxd_admin_role_module.updated_date
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_role_module.created_user
     *
     * @return the value of skxd_admin_role_module.created_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_role_module.created_user
     *
     * @param createdUser the value for skxd_admin_role_module.created_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skxd_admin_role_module.updated_user
     *
     * @return the value of skxd_admin_role_module.updated_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skxd_admin_role_module.updated_user
     *
     * @param updatedUser the value for skxd_admin_role_module.updated_user
     *
     * @mbggenerated Sun Nov 29 11:26:04 CST 2015
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser;
    }
}